export {default as Home} from './Home'
export {default as Signup} from './Signup'
export {default as Signin} from './Signin'
export {default as Transfer} from './Transfer'
export {default as Dashboard} from './Dashboard'